# Generated by Django 5.2.1 on 2025-10-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoroom',
            name='start_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
