# Generated by Django 5.2.1 on 2025-10-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_videoroom_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoroom',
            name='subject_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
